language: node_js
node_js:
  - "node"

script:
  - npm run lint
  - npm test


deploy:
  provider: heroku
  api_key:
    secure: "O+TcJO9qYPeX3C8+wsP8jkeB2TXFJztZdzl7mwKVnAJQOhCvwjCHk4UYDrtHfrtCh4YrgcCl2K4qtCaqxUU2kvF4rAdQVUhMwUDt6cKa0rKS/J7//yNd/xKXFiGfSie8QUWps4sfM+jH3O1fPdtJr4pPYEicIm5Q0iNMgrF/Tt0bsUZkgxkMG1YrnMMHRnZ9A0wijF0qfv0ya9RgZ8xFtMUBbC2i4OWMrDnaVrXJgm85Lt8xTOgJ+Hz1KE+QCv9UwCTkBf6BQZhvmCUgwCw4pGVA9Z6wJUPBMPPN2fh61DDuQ3KXS/k+SRhVeWiTiHQgSRDh4Ld4RK4EezRS+l/3JgZ6Xhfbx5tFWMCVzF+L0YyPufvQT/Rc9LIX6ZqH0/NQni3BvZkl+ZSiHyEbTa8ocknMZcjp8IbI9YHnRYInSRD9zd3c4jEvG9/mne4d0IcLrWDDC4ed49Mz/JeCslT3p6YeKBzcNkJ3N7+dVvZygWh0+jeMnZ9Nw0D9SFVJ/cO7kcJZEu2SzxQLjfUU4tGgV6J5YYxw5SPidJBEzxxZTOzDlUQxlO2WuTNXFqY0myBwUK1QYsNPdDXQNEgnkfmDgNtQuCn8vWCwVCF5Ou25b4/mi7JN8XH/W1FhXFwgp85B5if+XD4XnFZG8oMGHvc2//+36/PswM7bA4BWz3YhSE0="
